// <auto-generated />
using HundeLeksikon.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HundeLeksikon.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240613081348_InitialCreateV1")]
    partial class InitialCreateV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HundeLeksikon.Shared.HundeData", b =>
                {
                    b.Property<int>("HundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HundeId"));

                    b.Property<int>("FCIGrupper")
                        .HasColumnType("int");

                    b.Property<string>("HundeBeskrivelsen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HundeEnergi")
                        .HasColumnType("int");

                    b.Property<string>("HundeNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HundePelspleje")
                        .HasColumnType("int");

                    b.Property<int>("HundeStørrelse")
                        .HasColumnType("int");

                    b.Property<int>("HundeTemperament")
                        .HasColumnType("int");

                    b.HasKey("HundeId");

                    b.ToTable("HundeData");
                });
#pragma warning restore 612, 618
        }
    }
}
